### ISSUE TITLE
GraphQL Supported?

### ISSUE THREAD

**Issue by ssyberg** [muchisx/shopify-admin-postman#2]
I'm a bit confused by the GraphQL support here, I see the notes in various sections of the readme that it's not supported but there is mention of using the desktop app, which I'm using and I forked the collection, but I don't see anything under the forked collections and the "introspection" appears stuck in a forever loading state. Did I miss something?

Thanks!

**Comment by muchisx** [comment]
Hi @ssyberg !

For GraphQL I recommend you to go this route if you're a first timer:
https://www.shopify.com/partners/blog/getting-started-with-graphql


If you really want to use Postman, you'll have to use the Postman's Desktop client and use the GraphQL like this (two options):
- Use it directly from my public workspace (https://github.com/muchisx/shopify-admin-postman#web-view-collections). The variables you set there are still stored in your workspace, so they remain "private".
- You can manually create your own GraphQL "collection", it's really just the endpoint and setting up the secrets, the schema will be loaded automatically by Postman and you will be able to make queries in like 10 min if you do it correctly.

Note:
What you forked was only the rest, as there's a bug in postman where graphql collections can't be exported

**Comment by ssyberg** [comment]
Thanks! Just wanted to clarify I did fork the GraphQL as well and it was stuck in a loading introspection state. I was able to make my own collection that is working now.
